In [1]:
import pandas as pd

In [2]:
attempt_processed_df = pd.read_csv('./output/agg_attempt_merged_df.csv')

In [17]:
attempt_processed_df['stars'].unique()

array([ 3.,  2., nan,  1.])

In [ ]:
attempt_processed_df['stars_1'] = attempt_processed_df['stars'] == 1
attempt_processed_df['stars_2'] = attempt_processed_df['stars'] == 2
attempt_processed_df['stars_3'] = attempt_processed_df['stars'] == 3
attempt_processed_df['stars_NA'] = attempt_processed_df['stars'].isna()

In [ ]:
student_problem_df = attempt_processed_df.groupby(['studentRef', 'taskNumber']).agg(
        attempts=('attemptNumber', 'max'),
        total_replays=('replay_attempt', 'sum'),
        completed_attempts=('completed_dur_attempt', 'sum'),
        num_errors=('num_errors', 'sum'),
        num_hints=('num_hints', 'sum'),
        total_time_spent=('timeSpent', 'sum'),
        total_three_star=('stars_3', 'sum'),
        total_two_star=('stars_2', 'sum'),
        total_one_star=('stars_1', 'sum'),
        total_incomplete=('stars_NA', 'sum'),
        avg_stars=('stars', 'mean')
).reset_index()
student_problem_df['completed_attempts'] = student_problem_df['completed_attempts'].fillna(0).astype(int)
student_problem_df['total_replays'] = student_problem_df['total_replays'].fillna(
    0).astype(int)

In [5]:
student_problem_df.to_csv('./output/student_problem_level.csv', index=False)

In [ ]:
student_df  = student_problem_df.groupby('studentRef').agg(
    total_problems=('taskNumber', 'nunique'),
    total_attempts=('attempts', 'sum'),
    total_replays=('total_replays', 'sum'),
    total_completed_attempts=('completed_attempts', 'sum'),
    total_errors=('num_errors', 'sum'),
    total_hints=('num_hints', 'sum'),
    total_time_spent=('total_time_spent', 'sum'),
    total_one_star=('total_one_star', 'sum'),
    total_two_star=('total_two_star', 'sum'),
    total_three_star=('total_three_star', 'sum'),
    total_incomplete=('total_incomplete', 'sum'),
    avg_stars=('avg_stars', 'mean')
).reset_index()

In [7]:
student_df

,studentRef,total_problems,total_attempts,total_replays,total_completed_attempts,total_errors,total_hints,total_time_spent,total_one_star,total_two_star,total_three_star,avg_stars
0,689a3db5a5a0dcb0efbfe0d9,10,11.0,1,10,2,0,104.412,0,4,6,2.611111
1,689a5eb0339d724c4b85064d,12,15.0,0,11,2,0,325.132,0,1,10,2.909091
2,689b48fea5a0dcb0efc03e13,3,3.0,0,2,0,0,24.316,0,0,2,3.000000
3,689b5fd0a5a0dcb0efc04b46,36,36.0,0,36,4,1,396.308,0,3,33,2.916667
4,689b6c59a5a0dcb0efc04ecd,18,23.0,1,19,9,0,942.350,1,8,10,2.527778
...,...,...,...,...,...,...,...,...,...,...,...,...
804,68dfefd323d0a54e09102418,9,14.0,3,10,2,0,179.141,0,2,8,2.875000
805,68dff13e23d0a54e091138eb,36,72.0,10,42,54,2,1456.857,0,7,35,2.921429
806,68dff2bd7fb9e1f6ac52192e,6,6.0,0,5,1,0,121.705,0,2,3,2.600000
807,68e0069ef946085e8444873c,9,20.0,1,8,52,1,479.015,0,4,4,2.500000
808,68e0069ff946085e84448abb,29,45.0,2,30,13,4,1152.321,2,14,14,2.428571

In [8]:
student_df.describe()

,total_problems,total_attempts,total_replays,total_completed_attempts,total_errors,total_hints,total_time_spent,total_one_star,total_two_star,total_three_star,avg_stars
count,809.000000,809.000000,809.000000,809.000000,809.000000,809.000000,809.000000,809.000000,809.000000,809.000000,809.000000
mean,42.223733,71.767614,11.957973,48.301607,57.049444,5.503090,1812.383827,1.580964,11.254635,35.466007,2.722293
std,34.226902,70.642896,25.343447,43.743067,70.206573,10.248173,2330.470817,2.523392,9.811815,34.288802,0.189071
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,22.308000,0.000000,0.000000,0.000000,1.900000
25%,21.000000,39.000000,1.000000,25.000000,25.000000,0.000000,1141.628000,0.000000,6.000000,15.000000,2.607143
50%,33.000000,55.000000,5.000000,36.000000,42.000000,3.000000,1513.016000,1.000000,10.000000,25.000000,2.772727
75%,50.000000,77.000000,14.000000,55.000000,64.000000,7.000000,1815.611000,2.000000,13.000000,41.000000,2.875000
max,252.000000,769.000000,319.000000,409.000000,975.000000,191.000000,50614.276000,30.000000,125.000000,291.000000,3.000000

In [9]:
student_df['total_time_spent_mins'] = student_df['total_time_spent'] / 60

In [10]:
student_df.to_csv('./output/student_level_agg.csv', index=False)

In [11]:
student_df.describe().to_csv('./output/student_level_agg_summary.csv')

In [12]:
data_folder = "data/research-data-68dc2e6975d58c3b44b947d5-2025-10-02/"

roster_df = pd.read_json(data_folder+'roster-metadata.json')

In [13]:
roster_df

,sessionId,studentRef,classroomId,studentEmailPrefix,teacherId
0,689b80e9a5a0dcb0efc05a22,689a3bab339d724c4b84f220,689a3a351c2a3051d646fc15,pontecorvo.robert.inc,65d4cca1231a070013ea0390
1,689b80e9a5a0dcb0efc05a22,689a3db5a5a0dcb0efbfe0d9,689a3a351c2a3051d646fc15,erin.ottmar,65d4cca1231a070013ea0390
2,689b80e9a5a0dcb0efc05a22,689a5eb0339d724c4b85064d,689a3a351c2a3051d646fc15,awortman,65d4cca1231a070013ea0390
3,689b80e9a5a0dcb0efc05a22,689b445b1c2a3051d6476c5b,689a3a351c2a3051d646fc15,erik,65d4cca1231a070013ea0390
4,689b80e9a5a0dcb0efc05a22,689b48fea5a0dcb0efc03e13,689a3a351c2a3051d646fc15,xwei,65d4cca1231a070013ea0390
...,...,...,...,...,...
802,68de816c9c576abf144ce9d3,68b86eec4b63ee62858f8653,68b82ce4cd608fad6b864ace,207450,62d9645c6c2cd30013dbd10c
803,68de816c9c576abf144ce9d3,68b86ef04b63ee62858f8677,68b82ce4cd608fad6b864ace,156709,62d9645c6c2cd30013dbd10c
804,68de816c9c576abf144ce9d3,68b86ef0cd608fad6b88cbf6,68b82ce4cd608fad6b864ace,150999,62d9645c6c2cd30013dbd10c
805,68de816c9c576abf144ce9d3,68b86ef14b63ee62858f8699,68b82ce4cd608fad6b864ace,153312,62d9645c6c2cd30013dbd10c
806,68de816c9c576abf144ce9d3,68b867d5b4f70f7e6b61feb3,68b82ce4cd608fad6b864ace,153732,62d9645c6c2cd30013dbd10c

In [14]:
completed_students = student_df.query('total_problems == 252')

In [15]:
completed_students

,studentRef,total_problems,total_attempts,total_replays,total_completed_attempts,total_errors,total_hints,total_time_spent,total_one_star,total_two_star,total_three_star,avg_stars,total_time_spent_mins
103,68ade7cf6ac49894e3b59883,252,769.0,319,320,975,19,15875.364,8,59,253,2.898611,264.589400
106,68ade7f442606a064821a5b6,252,540.0,25,258,749,107,17811.043,28,57,173,2.567460,296.850717
112,68ade8146ac49894e3b5a176,252,714.0,291,409,551,49,16217.317,30,88,291,2.846745,270.288617

In [16]:
completed_students.merge(roster_df, on='studentRef', how='left')

,studentRef,total_problems,total_attempts,total_replays,total_completed_attempts,total_errors,total_hints,total_time_spent,total_one_star,total_two_star,total_three_star,avg_stars,total_time_spent_mins,sessionId,classroomId,studentEmailPrefix,teacherId
0,68ade7cf6ac49894e3b59883,252,769.0,319,320,975,19,15875.364,8,59,253,2.898611,264.589400,68daccd2b4f70f7e6bf25a3c,689b60aba5a0dcb0efc04b6c,206591,6883d08351ce0772f035172f
1,68ade7f442606a064821a5b6,252,540.0,25,258,749,107,17811.043,28,57,173,2.567460,296.850717,68daccd2b4f70f7e6bf25a3c,689b60aba5a0dcb0efc04b6c,164963,6883d08351ce0772f035172f
2,68ade8146ac49894e3b5a176,252,714.0,291,409,551,49,16217.317,30,88,291,2.846745,270.288617,68daccd2b4f70f7e6bf25a3c,689b60aba5a0dcb0efc04b6c,154415,6883d08351ce0772f035172f