In [1]:
import pandas as pd

In [2]:
attempt_processed_df = pd.read_csv('./output/agg_attempt_merged_df.csv')

In [3]:
attempt_processed_df['stars'].unique()

array([ 3.,  2., nan,  1.])

In [4]:
attempt_processed_df['stars_1'] = attempt_processed_df['stars'] == 1
attempt_processed_df['stars_2'] = attempt_processed_df['stars'] == 2
attempt_processed_df['stars_3'] = attempt_processed_df['stars'] == 3
attempt_processed_df['stars_NA'] = attempt_processed_df['stars'].isna()

In [5]:
student_problem_df = attempt_processed_df.groupby(['studentRef', 'taskNumber']).agg(
        attempts=('attemptNumber', 'max'),
        total_replays=('replay_attempt', 'sum'),
        completed_attempts=('completed_dur_attempt', 'sum'),
        num_errors=('num_errors', 'sum'),
        num_hints=('num_hints', 'sum'),
        total_time_spent=('timeSpent', 'sum'),
        total_three_star=('stars_3', 'sum'),
        total_two_star=('stars_2', 'sum'),
        total_one_star=('stars_1', 'sum'),
        total_incomplete=('stars_NA', 'sum'),
        avg_stars=('stars', 'mean')
).reset_index()
student_problem_df['completed_attempts'] = student_problem_df['completed_attempts'].fillna(0).astype(int)
student_problem_df['total_replays'] = student_problem_df['total_replays'].fillna(
    0).astype(int)

In [6]:
student_problem_df.to_csv('./output/student_problem_level.csv', index=False)

In [7]:
student_df  = student_problem_df.groupby('studentRef').agg(
    total_problems=('taskNumber', 'nunique'),
    total_attempts=('attempts', 'sum'),
    total_replays=('total_replays', 'sum'),
    total_completed_attempts=('completed_attempts', 'sum'),
    total_errors=('num_errors', 'sum'),
    total_hints=('num_hints', 'sum'),
    total_time_spent=('total_time_spent', 'sum'),
    total_one_star=('total_one_star', 'sum'),
    total_two_star=('total_two_star', 'sum'),
    total_three_star=('total_three_star', 'sum'),
    total_incomplete=('total_incomplete', 'sum'),
    avg_stars=('avg_stars', 'mean')
).reset_index()

In [14]:
student_df.describe()

,total_problems,total_attempts,total_replays,total_completed_attempts,total_errors,total_hints,total_time_spent,total_one_star,total_two_star,total_three_star,total_incomplete,avg_stars,total_time_spent_mins
count,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000
mean,65.298945,117.862837,21.674091,76.463072,103.869871,10.426729,2865.922204,2.670574,17.342321,56.450176,41.362251,2.728674,47.765370
std,52.431900,111.986884,39.207127,67.430595,146.674124,18.951404,3014.617075,3.869410,15.544576,51.532285,48.555484,0.177487,50.243618
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,24.316000,0.000000,0.000000,0.000000,0.000000,1.900000,0.405267
25%,28.000000,44.000000,1.000000,29.000000,36.000000,1.000000,1380.863000,0.000000,8.000000,17.000000,14.000000,2.611111,23.014383
50%,47.000000,70.000000,8.000000,50.000000,62.000000,5.000000,1848.478000,1.000000,12.000000,35.000000,24.000000,2.773810,30.807967
75%,100.000000,165.000000,24.000000,114.000000,130.000000,13.000000,3716.935000,4.000000,22.000000,88.000000,52.000000,2.874663,61.948917
max,252.000000,804.000000,388.000000,437.000000,2866.000000,343.000000,54308.393000,36.000000,160.000000,305.000000,449.000000,3.000000,905.139883

In [8]:
student_df

,studentRef,total_problems,total_attempts,total_replays,total_completed_attempts,total_errors,total_hints,total_time_spent,total_one_star,total_two_star,total_three_star,total_incomplete,avg_stars
0,689a3db5a5a0dcb0efbfe0d9,10,11.0,1,10,2,0,104.412,0,4,6,1,2.611111
1,689a5eb0339d724c4b85064d,12,15.0,0,11,2,0,325.132,0,1,10,4,2.909091
2,689b48fea5a0dcb0efc03e13,3,3.0,0,2,0,0,24.316,0,0,2,1,3.000000
3,689b5fd0a5a0dcb0efc04b46,36,36.0,0,36,4,1,396.308,0,3,33,0,2.916667
4,689b6c59a5a0dcb0efc04ecd,18,23.0,1,19,9,0,942.350,1,8,10,4,2.527778
...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,68dff7af7fb9e1f6ac570684,193,519.0,183,307,905,129,12665.225,24,94,189,212,2.839048
849,68e0069ef946085e8444873c,17,30.0,1,16,77,3,987.126,1,8,7,14,2.375000
850,68e0069ff946085e84448abb,36,56.0,4,40,16,7,1676.036,3,16,21,16,2.518519
851,68e7afcecb82aca6bd0d7af6,10,12.0,0,9,2,0,148.228,0,2,7,3,2.777778
852,68efff3a13aa4202389ad5b6,10,14.0,3,12,18,0,459.983,0,4,8,2,2.759259

In [9]:
student_df.describe()

,total_problems,total_attempts,total_replays,total_completed_attempts,total_errors,total_hints,total_time_spent,total_one_star,total_two_star,total_three_star,total_incomplete,avg_stars
count,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000,853.000000
mean,65.298945,117.862837,21.674091,76.463072,103.869871,10.426729,2865.922204,2.670574,17.342321,56.450176,41.362251,2.728674
std,52.431900,111.986884,39.207127,67.430595,146.674124,18.951404,3014.617075,3.869410,15.544576,51.532285,48.555484,0.177487
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,24.316000,0.000000,0.000000,0.000000,0.000000,1.900000
25%,28.000000,44.000000,1.000000,29.000000,36.000000,1.000000,1380.863000,0.000000,8.000000,17.000000,14.000000,2.611111
50%,47.000000,70.000000,8.000000,50.000000,62.000000,5.000000,1848.478000,1.000000,12.000000,35.000000,24.000000,2.773810
75%,100.000000,165.000000,24.000000,114.000000,130.000000,13.000000,3716.935000,4.000000,22.000000,88.000000,52.000000,2.874663
max,252.000000,804.000000,388.000000,437.000000,2866.000000,343.000000,54308.393000,36.000000,160.000000,305.000000,449.000000,3.000000

In [10]:
student_df['total_time_spent_mins'] = student_df['total_time_spent'] / 60

In [11]:
student_df.to_csv('./output/student_level_agg.csv', index=False)

In [12]:
student_df.describe().to_csv('./output/student_level_agg_summary.csv')

In [13]:
data_folder = "data/research-data-68dc2e6975d58c3b44b947d5-2025-10-02/"

roster_df = pd.read_json(data_folder+'roster-metadata.json')

FileNotFoundError: File data/research-data-68dc2e6975d58c3b44b947d5-2025-10-02/roster-metadata.json does not exist

In [ ]:
roster_df

,sessionId,studentRef,classroomId,studentEmailPrefix,teacherId
0,689b80e9a5a0dcb0efc05a22,689a3bab339d724c4b84f220,689a3a351c2a3051d646fc15,pontecorvo.robert.inc,65d4cca1231a070013ea0390
1,689b80e9a5a0dcb0efc05a22,689a3db5a5a0dcb0efbfe0d9,689a3a351c2a3051d646fc15,erin.ottmar,65d4cca1231a070013ea0390
2,689b80e9a5a0dcb0efc05a22,689a5eb0339d724c4b85064d,689a3a351c2a3051d646fc15,awortman,65d4cca1231a070013ea0390
3,689b80e9a5a0dcb0efc05a22,689b445b1c2a3051d6476c5b,689a3a351c2a3051d646fc15,erik,65d4cca1231a070013ea0390
4,689b80e9a5a0dcb0efc05a22,689b48fea5a0dcb0efc03e13,689a3a351c2a3051d646fc15,xwei,65d4cca1231a070013ea0390
...,...,...,...,...,...
802,68de816c9c576abf144ce9d3,68b86eec4b63ee62858f8653,68b82ce4cd608fad6b864ace,207450,62d9645c6c2cd30013dbd10c
803,68de816c9c576abf144ce9d3,68b86ef04b63ee62858f8677,68b82ce4cd608fad6b864ace,156709,62d9645c6c2cd30013dbd10c
804,68de816c9c576abf144ce9d3,68b86ef0cd608fad6b88cbf6,68b82ce4cd608fad6b864ace,150999,62d9645c6c2cd30013dbd10c
805,68de816c9c576abf144ce9d3,68b86ef14b63ee62858f8699,68b82ce4cd608fad6b864ace,153312,62d9645c6c2cd30013dbd10c
806,68de816c9c576abf144ce9d3,68b867d5b4f70f7e6b61feb3,68b82ce4cd608fad6b864ace,153732,62d9645c6c2cd30013dbd10c

In [ ]:
completed_students = student_df.query('total_problems == 252')

In [ ]:
completed_students

,studentRef,total_problems,total_attempts,total_replays,total_completed_attempts,total_errors,total_hints,total_time_spent,total_one_star,total_two_star,total_three_star,avg_stars,total_time_spent_mins
103,68ade7cf6ac49894e3b59883,252,769.0,319,320,975,19,15875.364,8,59,253,2.898611,264.589400
106,68ade7f442606a064821a5b6,252,540.0,25,258,749,107,17811.043,28,57,173,2.567460,296.850717
112,68ade8146ac49894e3b5a176,252,714.0,291,409,551,49,16217.317,30,88,291,2.846745,270.288617

In [ ]:
completed_students.merge(roster_df, on='studentRef', how='left')

,studentRef,total_problems,total_attempts,total_replays,total_completed_attempts,total_errors,total_hints,total_time_spent,total_one_star,total_two_star,total_three_star,avg_stars,total_time_spent_mins,sessionId,classroomId,studentEmailPrefix,teacherId
0,68ade7cf6ac49894e3b59883,252,769.0,319,320,975,19,15875.364,8,59,253,2.898611,264.589400,68daccd2b4f70f7e6bf25a3c,689b60aba5a0dcb0efc04b6c,206591,6883d08351ce0772f035172f
1,68ade7f442606a064821a5b6,252,540.0,25,258,749,107,17811.043,28,57,173,2.567460,296.850717,68daccd2b4f70f7e6bf25a3c,689b60aba5a0dcb0efc04b6c,164963,6883d08351ce0772f035172f
2,68ade8146ac49894e3b5a176,252,714.0,291,409,551,49,16217.317,30,88,291,2.846745,270.288617,68daccd2b4f70f7e6bf25a3c,689b60aba5a0dcb0efc04b6c,154415,6883d08351ce0772f035172f