In [11]:
import pandas as pd
import numpy as np
import json

In [12]:
data_folder = "data/research-data-68dc2e6975d58c3b44b947d5-2025-10-17/"
attempt_file = 'attempt-data.json'
event_file = 'event-logs.json'
roster_file = 'roster-metadata.json'
study_file = 'study-metadata.json'
task_file = 'task-metadata.json'

In [13]:
json.dumps(json.load(open(data_folder+study_file)), indent=4)

'{\n    "studyId": "68dc2e6975d58c3b44b947d5",\n    "studyName": "FH2T Forsyth 2025",\n    "studyDescription": "Official pilot study in Forsyth 2025.",\n    "hasStudentEmailPrefix": true\n}'

# Attempt Data checks

In [14]:
attempt_df = pd.read_json(data_folder + attempt_file)
attempt_df.columns

Index(['studentRef', 'studentSessionId', 'sessionId', 'taskWorkNumber',
       'taskWork', 'type', 'reflectiveAnswer', 'submitted', 'correct',
       'clientCreatedAtHlc', 'timeSpent', 'classlessCanvas', 'steps',
       'createdAt', 'updatedAt', 'resetAfterSubmit',
       'followsAResetAfterSubmit', 'reasonNotSubmitted', 'hintShown'],
      dtype='object')

In [15]:
attempt_cols = ['studentRef', 'sessionId', 'taskWorkNumber',
                'taskWork', 'submitted', 'correct',
                'clientCreatedAtHlc', 'timeSpent', 'steps']
attempt_df = attempt_df[attempt_cols]

In [16]:
placeholder_attempts_hlc = attempt_df.loc[(attempt_df['submitted'] == False) & (
    attempt_df['correct'] == True), 'clientCreatedAtHlc'].unique()
# remove placeholder attempts
attempt_df = attempt_df.loc[~((attempt_df['submitted'] == False) & (
    attempt_df['correct'] == True))]
attempt_df['timeSpent'] = attempt_df['timeSpent']/1000.0 # convert to seconds

In [17]:
attempt_df.head()

,studentRef,sessionId,taskWorkNumber,taskWork,submitted,correct,clientCreatedAtHlc,timeSpent,steps
0,689b48fea5a0dcb0efc03e13,689b80e9a5a0dcb0efc05a22,1,689b826f339d724c4b857148,True,True,001755021939887-0000-5VGMexfpA9LZCJkx9Cb2AS,7.668,1
2,689b48fea5a0dcb0efc03e13,689b80e9a5a0dcb0efc05a22,2,689b826f339d724c4b857149,True,True,001755021939891-0000-5VGMexfpA9LZCJkx9Cb2AS,16.626,3
4,689b48fea5a0dcb0efc03e13,689b80e9a5a0dcb0efc05a22,3,689b826f339d724c4b85714a,False,False,001755021939892-0000-5VGMexfpA9LZCJkx9Cb2AS,0.022,0
5,689a3db5a5a0dcb0efbfe0d9,689b80e9a5a0dcb0efc05a22,1,689b9143339d724c4b8599a0,True,True,001755025733352-0000-ksojKiVwW2HzDmXDKcfF5L,2.460,1
7,689a3db5a5a0dcb0efbfe0d9,689b80e9a5a0dcb0efc05a22,2,689b9143339d724c4b8599a1,True,True,001755025733356-0000-ksojKiVwW2HzDmXDKcfF5L,10.835,3

# Event log data

In [18]:
# load eventLogs
event_df = pd.read_json(data_folder + event_file)
print(event_df.columns)
print(event_df['eventType'].unique())
event_df.head()

Index(['_id', 'studentRef', 'sessionId', 'taskNumber', 'attemptNumber', 'uid',
       'visitId', 'timestamp', 'studentSessionId', 'eventType', 'attemptHlc',
       'oldState', 'newState', 'actionId', 'actionName', 'method', 'steps',
       'stars', 'mistake', 'targetMathSel', 'dropClosestToSelf', 'selector',
       'side', 'dx', 'dy', 'wasSolved', 'reason', 'enteredLatex',
       'shakeLatex'],
      dtype='object')
['visitGameScreen' 'visitTask' 'mathStep' 'solvedTask' 'mathMistake'
 'resetTask' 'showHint' 'hideHint']

,_id,studentRef,sessionId,taskNumber,attemptNumber,uid,visitId,timestamp,studentSessionId,eventType,...,targetMathSel,dropClosestToSelf,selector,side,dx,dy,wasSolved,reason,enteredLatex,shakeLatex
0,689b826f339d724c4b857147,689b48fea5a0dcb0efc03e13,689b80e9a5a0dcb0efc05a22,NaN,NaN,3FAY639E5VqVRfcQqXtjr6,jEaShXyueBdqMfBLrrShje,2025-08-12 18:05:35.621,689b826f339d724c4b857147,visitGameScreen,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,689b826f339d724c4b857147,689b48fea5a0dcb0efc03e13,689b80e9a5a0dcb0efc05a22,1.0,1.0,trmJ4JHbyVybdJCsq7YVtf,jEaShXyueBdqMfBLrrShje,2025-08-12 18:05:39.955,689b826f339d724c4b857147,visitTask,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,689b826f339d724c4b857147,689b48fea5a0dcb0efc03e13,689b80e9a5a0dcb0efc05a22,1.0,1.0,jEPaEuB5gXxsMA3R4XLsHm,jEaShXyueBdqMfBLrrShje,2025-08-12 18:05:46.758,689b826f339d724c4b857147,mathStep,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,689b826f339d724c4b857147,689b48fea5a0dcb0efc03e13,689b80e9a5a0dcb0efc05a22,1.0,1.0,j4Er5qy5ZkeE71ULmteoeC,jEaShXyueBdqMfBLrrShje,2025-08-12 18:05:47.605,689b826f339d724c4b857147,solvedTask,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,689b826f339d724c4b857147,689b48fea5a0dcb0efc03e13,689b80e9a5a0dcb0efc05a22,2.0,1.0,pqiTxhfNUANGB1c8h3JXGz,jEaShXyueBdqMfBLrrShje,2025-08-12 18:05:50.880,689b826f339d724c4b857147,visitTask,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# cols of interest for aggregation
event_cols_to_keep = ['studentRef', 'taskNumber',
                      'attemptNumber', 'eventType', 'timestamp', 'mistake', 'stars', 'attemptHlc']
# user interaction events: math actions, mistake events or hint events
action_events = ['mathStep', 'mathMistake', 'hideHint', 'showHint']
event_df = event_df[event_cols_to_keep]

In [20]:
event_df = event_df.sort_values(
    by=['studentRef', 'taskNumber', 'attemptNumber', 'timestamp'])

In [21]:
event_df.loc[:, 'previous_timestamp'] = event_df.groupby(
    ['studentRef', 'taskNumber'])['timestamp'].shift(1)
event_df['delta_time'] = event_df['timestamp'] - event_df['previous_timestamp']
event_df['delta_time_tuple'] = list(
    zip(event_df['delta_time'], event_df['eventType'].isin(action_events)))

In [22]:
# remove redundant eventTypes: 'visitGameScreen'
event_df = event_df.loc[~event_df['eventType'].isin(['visitGameScreen'])]

In [23]:
# TODO next time use attemptHlc to group
event_grouped = event_df.groupby(['studentRef', 'taskNumber', 'attemptNumber'])

In [24]:
def get_pause_time(col: pd.Series) -> float:
    col = col.apply(pd.Series) # expand tuples
    action_times = col.loc[col[1] == True, 0]
    if len(action_times) == 0:
        return None
    else:
        return action_times.iloc[0].total_seconds()

def get_validity_first_step(col:pd.Series) -> bool:
    is_mistake = col == 'mathMistake'

    is_math_step = col == 'mathStep'
    if not is_math_step.any(): # if no math steps
        return None
    elif not is_mistake.any():  # if no math mistakes and at least one math step
        return True
    else:
        first_mistake_index = is_mistake.idxmax()
        first_math_step_index = is_math_step.idxmax()
        return first_math_step_index < first_mistake_index
    
def get_replay_attempt(completed_dur_attempt:pd.Series) -> pd.Series:
    if not completed_dur_attempt.any():
        return pd.Series([False]*len(completed_dur_attempt))
    else:
        first_completed_index = completed_dur_attempt.idxmax()
        return completed_dur_attempt.index > first_completed_index

In [25]:
# stage one: info from all event types
attempt_agg_df = event_grouped.agg(
    start_time=('timestamp', 'first'),
    # end time needs to ignore time after solvingTask (e.g. reset)
    end_time=('timestamp', 'last'), # need to account for time after solving task and waiting before next attempt or moving on. 
    total_time = ('timestamp', lambda x: (x.iloc[-1] - x.iloc[0]).total_seconds()),
    pause_time=('delta_time_tuple', get_pause_time),
    num_steps = ('eventType', lambda x: (x == 'mathStep').sum()),
    num_errors=('eventType', lambda x: (x == 'mathMistake').sum()),
    num_keypad_errors=('mistake', lambda x: (x == 'keypad').sum()),
    num_shaking_errors=('mistake', lambda x: (x == 'tap').sum()),
    num_snapping_errors=('mistake', lambda x: (x == 'drag').sum()),
    num_hints = ('eventType', lambda x: (x == 'showHint').sum()),
    completed_dur_attempt=('eventType', lambda x: (x == 'solvedTask').any()),
    stars=('stars', 'max'),
    num_visits=('eventType', lambda x: (x == 'visitTask').sum()),
    validity_first_step = ('eventType', get_validity_first_step),
    attemptHlc=('attemptHlc', lambda x: x.mode().iloc[0]),
).reset_index()
attempt_agg_df['pause_time_ratio'] = attempt_agg_df['pause_time'] / attempt_agg_df['total_time']
attempt_agg_df['replay_attempt'] = attempt_agg_df.groupby(['studentRef', 'taskNumber'])[
    'completed_dur_attempt'].transform(get_replay_attempt)

In [26]:
attempt_agg_df

,studentRef,taskNumber,attemptNumber,start_time,end_time,total_time,pause_time,num_steps,num_errors,num_keypad_errors,num_shaking_errors,num_snapping_errors,num_hints,completed_dur_attempt,stars,num_visits,validity_first_step,attemptHlc,pause_time_ratio,replay_attempt
0,689a3db5a5a0dcb0efbfe0d9,1.0,1.0,2025-08-12 19:08:53.410,2025-08-12 19:08:55.855,2.445,1.863,1,0,0,0,0,0,True,3.0,1,True,001755025733352-0000-ksojKiVwW2HzDmXDKcfF5L,0.761963,False
1,689a3db5a5a0dcb0efbfe0d9,2.0,1.0,2025-08-12 19:08:58.870,2025-08-12 19:09:12.695,13.825,4.069,3,1,0,0,1,0,True,3.0,1,False,001755025733356-0000-ksojKiVwW2HzDmXDKcfF5L,0.294322,False
2,689a3db5a5a0dcb0efbfe0d9,2.0,2.0,2025-08-12 19:09:13.975,2025-08-12 19:09:22.000,8.025,1.280,4,0,0,0,0,0,True,2.0,0,True,001755025749689-0000-ksojKiVwW2HzDmXDKcfF5L,0.159502,True
3,689a3db5a5a0dcb0efbfe0d9,3.0,1.0,2025-08-12 19:09:25.145,2025-08-12 19:09:37.180,12.035,8.754,2,0,0,0,0,0,True,3.0,1,True,001755025733358-0000-ksojKiVwW2HzDmXDKcfF5L,0.727378,False
4,689a3db5a5a0dcb0efbfe0d9,4.0,1.0,2025-08-12 19:09:40.356,2025-08-12 19:09:51.830,11.474,8.648,3,0,0,0,0,0,True,3.0,1,True,001755025733358-0001-ksojKiVwW2HzDmXDKcfF5L,0.753704,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100605,68efff3a13aa4202389ad5b6,6.0,1.0,2025-10-17 01:12:54.029,2025-10-17 01:15:06.436,132.407,127.520,2,2,0,1,1,0,True,3.0,1,True,001760663285789-0002-qfyVvXHFY6WWv8mxF2JH3W,0.963091,False
100606,68efff3a13aa4202389ad5b6,7.0,1.0,2025-10-17 01:15:10.442,2025-10-17 01:15:22.912,12.470,7.268,1,1,0,1,0,0,True,3.0,1,False,001760663285789-0003-qfyVvXHFY6WWv8mxF2JH3W,0.582839,False
100607,68efff3a13aa4202389ad5b6,8.0,1.0,2025-10-17 01:15:26.391,2025-10-17 01:16:31.592,65.201,56.236,2,1,0,1,0,0,True,3.0,1,False,001760663285789-0004-qfyVvXHFY6WWv8mxF2JH3W,0.862502,False
100608,68efff3a13aa4202389ad5b6,9.0,1.0,2025-10-17 01:16:35.211,2025-10-17 13:21:04.408,43469.197,119.739,5,8,2,6,0,0,True,2.0,2,False,001760663285789-0005-qfyVvXHFY6WWv8mxF2JH3W,0.002755,False
100609,68efff3a13aa4202389ad5b6,10.0,1.0,2025-10-17 13:21:07.399,2025-10-17 13:30:08.018,540.619,264.712,2,1,0,1,0,0,False,NaN,1,True,001760706894577-0000-5Z8DwYm4R2ZzPcvJz4TMm6,0.489646,NaN

# Check attempt and aggregated attempt merge

In [27]:
attempt_merge_df = pd.merge(attempt_agg_df, attempt_df[attempt_df.columns.difference(['studentRef'])],
                            how='inner',
                            left_on='attemptHlc', right_on='clientCreatedAtHlc')
attempt_merge_df.drop(columns=['clientCreatedAtHlc', 'taskWork', 'taskWorkNumber'], inplace=True)

In [28]:
len(attempt_merge_df)

100505

In [29]:
attempt_merge_df.taskNumber.value_counts()

taskNumber
9.0      2637
25.0     2379
15.0     2173
16.0     1889
14.0     1866
         ...
248.0       8
239.0       7
240.0       6
241.0       6
249.0       6
Name: count, Length: 252, dtype: int64

In [30]:
attempt_merge_df.to_csv('./output/agg_attempt_merged_df.csv', index=False)

# Checking Roster data

In [31]:
roster_df = pd.read_json(data_folder + roster_file)
roster_df

,sessionId,studentRef,classroomId,studentEmailPrefix,teacherId
0,689b80e9a5a0dcb0efc05a22,689a3bab339d724c4b84f220,689a3a351c2a3051d646fc15,pontecorvo.robert.inc,65d4cca1231a070013ea0390
1,689b80e9a5a0dcb0efc05a22,689a3db5a5a0dcb0efbfe0d9,689a3a351c2a3051d646fc15,erin.ottmar,65d4cca1231a070013ea0390
2,689b80e9a5a0dcb0efc05a22,689a5eb0339d724c4b85064d,689a3a351c2a3051d646fc15,awortman,65d4cca1231a070013ea0390
3,689b80e9a5a0dcb0efc05a22,689b445b1c2a3051d6476c5b,689a3a351c2a3051d646fc15,erik,65d4cca1231a070013ea0390
4,689b80e9a5a0dcb0efc05a22,689b48fea5a0dcb0efc03e13,689a3a351c2a3051d646fc15,xwei,65d4cca1231a070013ea0390
...,...,...,...,...,...
924,68f021fda560208b471027f9,68da8c61cd608fad6b0d787a,68d369ebcd608fad6bfa7b75,147620,68843ab351ce0772f035f738
925,68f021fda560208b471027f9,68da8ccacd608fad6b0d8e9a,68d369ebcd608fad6bfa7b75,131850,68843ab351ce0772f035f738
926,68f021fda560208b471027f9,68ed01bb13aa4202385bf5a8,68d369ebcd608fad6bfa7b75,152392,68843ab351ce0772f035f738
927,68f021fda560208b471027f9,68ed029f13aa4202385c03c2,68d369ebcd608fad6bfa7b75,152293,68843ab351ce0772f035f738
928,68f021fda560208b471027f9,68dad3bdb4f70f7e6bf29c23,68d369ebcd608fad6bfa7b75,144585,68843ab351ce0772f035f738

# Task Metadata

In [32]:
task_df = pd.read_json(data_folder + task_file)
task_df.columns

Index(['sessionCode', 'chapterNumber', 'taskNumberWithinChapter', 'taskId',
       'chapterId', 'chapterName', 'taskNumber', 'type', 'promptText',
       'promptHtml', 'sessionId', 'sessionCreatedAt', 'hideGoal',
       'allowCommutedAnswers', 'hintDelta', 'hintHtml', 'hintText',
       'optimalSteps', 'startState', 'goalState', 'reflectiveQuestion'],
      dtype='object')

In [33]:
type(task_df.loc[task_df["sessionCreatedAt"] == task_df["sessionCreatedAt"].max(), "sessionId"].iloc[0])

str

In [34]:
attempt_merge_df_check = attempt_merge_df.loc[attempt_merge_df['studentRef'].isin(
    ['68cc64e94b63ee6285e23ef4', '68cc6a8ab4f70f7e6bb505de'])].merge(roster_df, on='studentRef', how='inner')

In [35]:
attempt_merge_df_check[['studentEmailPrefix', 'taskNumber', 'attemptNumber', 'submitted', 'correct', 'completed_dur_attempt', 'stars', 'timeSpent', 'total_time', 'pause_time','num_steps', 'num_errors', 'num_hints', 'stars', 'validity_first_step']]

,studentEmailPrefix,taskNumber,attemptNumber,submitted,correct,completed_dur_attempt,stars,timeSpent,total_time,pause_time,num_steps,num_errors,num_hints,stars,validity_first_step
0,pyzhang2901,1.0,1.0,True,True,True,2.0,60.474,624.583,62.071,3,0,0,2.0,True
1,pyzhang2901,1.0,2.0,True,True,True,3.0,26.698,416.813,19.888,1,0,0,3.0,True
2,pyzhang2901,1.0,3.0,False,False,False,NaN,12.703,8.026,4.691,1,0,0,NaN,True
3,pyzhang2901,1.0,4.0,True,True,True,3.0,5.783,0.710,5.068,1,0,0,3.0,True
4,pyzhang2901,2.0,1.0,False,False,False,NaN,21.808,21.799,13.670,2,0,0,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,taehasongwpi,20.0,1.0,False,False,False,NaN,19.459,19.451,14.221,1,0,0,NaN,True
126,taehasongwpi,20.0,2.0,False,False,False,NaN,2.867,1.626,1.241,1,0,0,NaN,True
127,taehasongwpi,20.0,3.0,True,True,True,3.0,6.005,52.808,5.277,1,0,0,3.0,True
128,taehasongwpi,20.0,4.0,True,True,True,2.0,13.310,13.433,5.969,2,0,1,2.0,True
129,taehasongwpi,21.0,1.0,False,False,False,NaN,11.025,0.000,NaN,0,0,0,NaN,None

In [36]:
event_df

,studentRef,taskNumber,attemptNumber,eventType,timestamp,mistake,stars,attemptHlc,previous_timestamp,delta_time,delta_time_tuple
16,689a3db5a5a0dcb0efbfe0d9,1.0,1.0,visitTask,2025-08-12 19:08:53.410,NaN,NaN,001755025733352-0000-ksojKiVwW2HzDmXDKcfF5L,NaT,NaT,"(NaT, False)"
17,689a3db5a5a0dcb0efbfe0d9,1.0,1.0,mathStep,2025-08-12 19:08:55.273,NaN,NaN,001755025733352-0000-ksojKiVwW2HzDmXDKcfF5L,2025-08-12 19:08:53.410,0 days 00:00:01.863000,"(0 days 00:00:01.863000, True)"
18,689a3db5a5a0dcb0efbfe0d9,1.0,1.0,solvedTask,2025-08-12 19:08:55.855,NaN,3.0,001755025733352-0000-ksojKiVwW2HzDmXDKcfF5L,2025-08-12 19:08:55.273,0 days 00:00:00.582000,"(0 days 00:00:00.582000, False)"
19,689a3db5a5a0dcb0efbfe0d9,2.0,1.0,visitTask,2025-08-12 19:08:58.870,NaN,NaN,001755025733356-0000-ksojKiVwW2HzDmXDKcfF5L,NaT,NaT,"(NaT, False)"
20,689a3db5a5a0dcb0efbfe0d9,2.0,1.0,mathMistake,2025-08-12 19:09:02.939,drag,NaN,001755025733356-0000-ksojKiVwW2HzDmXDKcfF5L,2025-08-12 19:08:58.870,0 days 00:00:04.069000,"(0 days 00:00:04.069000, True)"
...,...,...,...,...,...,...,...,...,...,...,...
365734,68efff3a13aa4202389ad5b6,9.0,1.0,solvedTask,2025-10-17 13:21:04.408,NaN,2.0,001760663285789-0005-qfyVvXHFY6WWv8mxF2JH3W,2025-10-17 13:21:02.682,0 days 00:00:01.726000,"(0 days 00:00:01.726000, False)"
365735,68efff3a13aa4202389ad5b6,10.0,1.0,visitTask,2025-10-17 13:21:07.399,NaN,NaN,001760706894577-0000-5Z8DwYm4R2ZzPcvJz4TMm6,NaT,NaT,"(NaT, False)"
365736,68efff3a13aa4202389ad5b6,10.0,1.0,mathStep,2025-10-17 13:25:32.111,NaN,NaN,001760706894577-0000-5Z8DwYm4R2ZzPcvJz4TMm6,2025-10-17 13:21:07.399,0 days 00:04:24.712000,"(0 days 00:04:24.712000, True)"
365737,68efff3a13aa4202389ad5b6,10.0,1.0,mathMistake,2025-10-17 13:25:35.132,tap,NaN,001760706894577-0000-5Z8DwYm4R2ZzPcvJz4TMm6,2025-10-17 13:25:32.111,0 days 00:00:03.021000,"(0 days 00:00:03.021000, True)"
365738,68efff3a13aa4202389ad5b6,10.0,1.0,mathStep,2025-10-17 13:30:08.018,NaN,NaN,001760706894577-0000-5Z8DwYm4R2ZzPcvJz4TMm6,2025-10-17 13:25:35.132,0 days 00:04:32.886000,"(0 days 00:04:32.886000, True)"

In [37]:
event_df[(event_df['studentRef'] ==
         '68cc64e94b63ee6285e23ef4') & (event_df['taskNumber'] == 8)]

,studentRef,taskNumber,attemptNumber,eventType,timestamp,mistake,stars,attemptHlc,previous_timestamp,delta_time,delta_time_tuple
811,68cc64e94b63ee6285e23ef4,8.0,1.0,visitTask,2025-09-18 20:57:09.546,NaN,NaN,001758226030586-0006-tfFRg6YpMGMqg8oyYSL44f,NaT,NaT,"(NaT, False)"
812,68cc64e94b63ee6285e23ef4,8.0,1.0,mathStep,2025-09-18 20:57:14.854,NaN,NaN,001758226030586-0006-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 20:57:09.546,0 days 00:00:05.308000,"(0 days 00:00:05.308000, True)"
813,68cc64e94b63ee6285e23ef4,8.0,1.0,mathStep,2025-09-18 20:57:17.454,NaN,NaN,001758226030586-0006-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 20:57:14.854,0 days 00:00:02.600000,"(0 days 00:00:02.600000, True)"
814,68cc64e94b63ee6285e23ef4,8.0,1.0,solvedTask,2025-09-18 20:57:18.250,NaN,3.0,001758226030586-0006-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 20:57:17.454,0 days 00:00:00.796000,"(0 days 00:00:00.796000, False)"
815,68cc64e94b63ee6285e23ef4,8.0,1.0,resetTask,2025-09-18 20:58:23.872,NaN,NaN,001758226030586-0006-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 20:57:18.250,0 days 00:01:05.622000,"(0 days 00:01:05.622000, False)"
816,68cc64e94b63ee6285e23ef4,8.0,2.0,mathStep,2025-09-18 20:58:28.408,NaN,NaN,001758229038250-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 20:58:23.872,0 days 00:00:04.536000,"(0 days 00:00:04.536000, True)"
817,68cc64e94b63ee6285e23ef4,8.0,2.0,resetTask,2025-09-18 20:58:34.296,NaN,NaN,001758229038250-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 20:58:28.408,0 days 00:00:05.888000,"(0 days 00:00:05.888000, False)"
818,68cc64e94b63ee6285e23ef4,8.0,3.0,mathStep,2025-09-18 20:59:12.309,NaN,NaN,001758229114297-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 20:58:34.296,0 days 00:00:38.013000,"(0 days 00:00:38.013000, True)"
819,68cc64e94b63ee6285e23ef4,8.0,3.0,mathStep,2025-09-18 20:59:14.766,NaN,NaN,001758229114297-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 20:59:12.309,0 days 00:00:02.457000,"(0 days 00:00:02.457000, True)"
820,68cc64e94b63ee6285e23ef4,8.0,3.0,solvedTask,2025-09-18 20:59:15.556,NaN,3.0,001758229114297-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 20:59:14.766,0 days 00:00:00.790000,"(0 days 00:00:00.790000, False)"
821,68cc64e94b63ee6285e23ef4,8.0,3.0,resetTask,2025-09-18 21:00:29.008,NaN,NaN,001758229114297-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 20:59:15.556,0 days 00:01:13.452000,"(0 days 00:01:13.452000, False)"
822,68cc64e94b63ee6285e23ef4,8.0,4.0,mathStep,2025-09-18 21:00:33.373,NaN,NaN,001758229155557-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:00:29.008,0 days 00:00:04.365000,"(0 days 00:00:04.365000, True)"
823,68cc64e94b63ee6285e23ef4,8.0,4.0,resetTask,2025-09-18 21:00:42.312,NaN,NaN,001758229155557-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:00:33.373,0 days 00:00:08.939000,"(0 days 00:00:08.939000, False)"
824,68cc64e94b63ee6285e23ef4,8.0,5.0,mathStep,2025-09-18 21:00:52.734,NaN,NaN,001758229242313-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:00:42.312,0 days 00:00:10.422000,"(0 days 00:00:10.422000, True)"
825,68cc64e94b63ee6285e23ef4,8.0,5.0,mathStep,2025-09-18 21:00:57.732,NaN,NaN,001758229242313-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:00:52.734,0 days 00:00:04.998000,"(0 days 00:00:04.998000, True)"
826,68cc64e94b63ee6285e23ef4,8.0,5.0,solvedTask,2025-09-18 21:00:58.707,NaN,3.0,001758229242313-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:00:57.732,0 days 00:00:00.975000,"(0 days 00:00:00.975000, False)"
827,68cc64e94b63ee6285e23ef4,8.0,5.0,resetTask,2025-09-18 21:02:52.461,NaN,NaN,001758229242313-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:00:58.707,0 days 00:01:53.754000,"(0 days 00:01:53.754000, False)"
828,68cc64e94b63ee6285e23ef4,8.0,6.0,mathStep,2025-09-18 21:02:57.876,NaN,NaN,001758229258708-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:02:52.461,0 days 00:00:05.415000,"(0 days 00:00:05.415000, True)"
829,68cc64e94b63ee6285e23ef4,8.0,6.0,mathMistake,2025-09-18 21:03:12.414,drag,NaN,001758229258708-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:02:57.876,0 days 00:00:14.538000,"(0 days 00:00:14.538000, True)"
830,68cc64e94b63ee6285e23ef4,8.0,6.0,mathStep,2025-09-18 21:03:24.038,NaN,NaN,001758229258708-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:03:12.414,0 days 00:00:11.624000,"(0 days 00:00:11.624000, True)"
831,68cc64e94b63ee6285e23ef4,8.0,6.0,solvedTask,2025-09-18 21:03:24.816,NaN,3.0,001758229258708-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:03:24.038,0 days 00:00:00.778000,"(0 days 00:00:00.778000, False)"
832,68cc64e94b63ee6285e23ef4,8.0,6.0,resetTask,2025-09-18 21:04:36.188,NaN,NaN,001758229258708-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:03:24.816,0 days 00:01:11.372000,"(0 days 00:01:11.372000, False)"
833,68cc64e94b63ee6285e23ef4,8.0,7.0,mathStep,2025-09-18 21:04:41.556,NaN,NaN,001758229404817-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:04:36.188,0 days 00:00:05.368000,"(0 days 00:00:05.368000, True)"
834,68cc64e94b63ee6285e23ef4,8.0,7.0,mathMistake,2025-09-18 21:04:48.694,drag,NaN,001758229404817-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:04:41.556,0 days 00:00:07.138000,"(0 days 00:00:07.138000, True)"
835,68cc64e94b63ee6285e23ef4,8.0,7.0,mathStep,2025-09-18 21:04:53.116,NaN,NaN,001758229404817-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:04:48.694,0 days 00:00:04.422000,"(0 days 00:00:04.422000, True)"
836,68cc64e94b63ee6285e23ef4,8.0,7.0,solvedTask,2025-09-18 21:04:53.826,NaN,3.0,001758229404817-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:04:53.116,0 days 00:00:00.710000,"(0 days 00:00:00.710000, False)"
965,68cc64e94b63ee6285e23ef4,8.0,7.0,resetTask,2025-09-18 21:41:50.624,NaN,NaN,001758229404817-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:04:53.826,0 days 00:36:56.798000,"(0 days 00:36:56.798000, False)"
964,68cc64e94b63ee6285e23ef4,8.0,8.0,visitTask,2025-09-18 21:41:50.340,NaN,NaN,001758229493827-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:41:50.624,-1 days +23:59:59.716000,"(-1 days +23:59:59.716000, False)"
966,68cc64e94b63ee6285e23ef4,8.0,8.0,mathStep,2025-09-18 21:42:00.679,NaN,NaN,001758229493827-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:41:50.340,0 days 00:00:10.339000,"(0 days 00:00:10.339000, True)"
967,68cc64e94b63ee6285e23ef4,8.0,8.0,mathMistake,2025-09-18 21:42:02.225,tap,NaN,001758229493827-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:42:00.679,0 days 00:00:01.546000,"(0 days 00:00:01.546000, True)"
968,68cc64e94b63ee6285e23ef4,8.0,8.0,mathMistake,2025-09-18 21:42:03.559,tap,NaN,001758229493827-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:42:02.225,0 days 00:00:01.334000,"(0 days 00:00:01.334000, True)"
969,68cc64e94b63ee6285e23ef4,8.0,8.0,mathMistake,2025-09-18 21:42:05.223,tap,NaN,001758229493827-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:42:03.559,0 days 00:00:01.664000,"(0 days 00:00:01.664000, True)"
970,68cc64e94b63ee6285e23ef4,8.0,8.0,showHint,2025-09-18 21:42:31.190,NaN,NaN,001758229493827-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:42:05.223,0 days 00:00:25.967000,"(0 days 00:00:25.967000, True)"
971,68cc64e94b63ee6285e23ef4,8.0,8.0,mathStep,2025-09-18 21:42:52.554,NaN,NaN,001758229493827-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:42:31.190,0 days 00:00:21.364000,"(0 days 00:00:21.364000, True)"
972,68cc64e94b63ee6285e23ef4,8.0,8.0,mathStep,2025-09-18 21:42:58.400,NaN,NaN,001758229493827-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:42:52.554,0 days 00:00:05.846000,"(0 days 00:00:05.846000, True)"
973,68cc64e94b63ee6285e23ef4,8.0,8.0,mathStep,2025-09-18 21:43:00.477,NaN,NaN,001758229493827-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:42:58.400,0 days 00:00:02.077000,"(0 days 00:00:02.077000, True)"
974,68cc64e94b63ee6285e23ef4,8.0,8.0,solvedTask,2025-09-18 21:43:01.444,NaN,2.0,001758229493827-0000-tfFRg6YpMGMqg8oyYSL44f,2025-09-18 21:43:00.477,0 days 00:00:00.967000,"(0 days 00:00:00.967000, False)"